version: "3.7"
services:
  mongo_gui:
    image: mongo-express
    container_name: "mongo_gui"
    volumes:
      - mongo_gui:/data/db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongo_network
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo_test
    volumes:
      - mongo_db:/mongo_gui
    networks:
      - mongo_network
networks:
  mongo_network:
    name: mongo_network
volumes:
  mongo_db:
  mongo_gui:
